services:
  doc-api:
    build: .
    container_name: doc-api
    ports:
      - "8000:8000"
    environment:
      EXTRACTOR_MODE: ${EXTRACTOR_MODE:-hf}
      USE_GPU: ${USE_GPU:-0}
      OCR_CONF_THRESHOLD: ${OCR_CONF_THRESHOLD:-0.20}
      OCR_MIN_BOX_AREA: ${OCR_MIN_BOX_AREA:-60}
      HF_MODEL: ${HF_MODEL:-Qwen/Qwen2.5-0.5B-Instruct}
      LLM_BASE_URL: ${LLM_BASE_URL:-}
      LLM_API_KEY: ${LLM_API_KEY:-}
      LLM_MODEL: ${LLM_MODEL:-qwen2.5:7b-instruct}
      OUTPUT_DIR: /app/outputs
    volumes:
      - ./outputs:/app/outputs
